
meta_product_name: "TravelMap"
meta_title: "Travelmap - Get inspired"
meta_description: "Get inspired by fellow TravelMappers & inspire others by sharing your own experiences"
meta_image: "logo.png" # should exist in `app/assets/images/`

