
meta_product_name: "TravelMap"
meta_title: "TravelMap - Get inspired"
meta_description: "Get inspired by fellow TravelMappers & inspire others by sharing your own experiences"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
